import apiApp from "@gamer/api/worker";
// Generated by `opennextjs-cloudflare build` (pages:build) before this file is bundled by wrangler.
// @ts-expect-error - only exists after the build step, not at type-check time
import webHandler from "./.open-next/worker.js";

export default {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname.startsWith("/api/")) {
      return apiApp.fetch(request, env, ctx);
    }
    return webHandler.fetch(request, env, ctx);
  },
};
