name = "gamer-hub"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
run_worker_first = ["/*", "!/_next/*"]

[[routes]]
pattern = "gameer.com.ar/*"
zone_id = "3da753fd4dce5b24bd2aa3efeaf5bfdf"

[[routes]]
pattern = "paranagamejam.com.ar/*"
zone_id = "7add1ceab6c4ce00f4f30ff69c470896"
